title: Mathias Madsen


baseurl: "/ACD25-Portfolio-matbm01-dotcom" 
color_scheme: light 


description: ACD-E25 Portfolio
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true