title: Mathias Madsen

# Set baseurl to your repo name for project pages (e.g., "/ACD-Portfolio")
baseurl: "/ACD-Portfolio" # EDIT THIS FIELD

color_scheme: light 


description: ACD-E25 Portfolio
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true